### ISSUE TITLE
Environment Configured Credential Chains

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-crt-swift#100]
### Describe the feature

--/seps/accepted/shared/environment-chain.md

### Use Case

AWS_CREDENTIAL_PROVIDER_CHAIN env var configured credentials chain.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by waahm7** [comment]
This feature is not supported by any SDK yet. We can recreate the issue when we want to support it. Closing for now.
