### ISSUE TITLE
aws-crt-swift crashes when used together with swiftc flag -enable-experimental-cxx-interop

### ISSUE THREAD

**Issue by PeterWaIIace** [awslabs/aws-crt-swift#166]
### Describe the bug

aws-cert-swift crashes when used together with swiftc flag -enable-experimental-cxx-interop. 

It finds problem with using of .inl files together with C files.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/40773550/221190361-29a517c3-a5ef-42e4-b6b5-02a156c13db4.png">

Example error: `Import of C++ module 'AwsCCommon' appears within extern "C" language linkage specification`

As it is experimental feature, do not expect immediate bug fix but it would be extremely nice to be able to use swift packages together with Cpp sources. 

### Expected Behavior

Successful compilation.

### Current Behavior

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/40773550/221190361-29a517c3-a5ef-42e4-b6b5-02a156c13db4.png">

### Reproduction Steps

add to swift compiler flags: `-enable-experimental-cxx-interop`

### AWS CRT SWIFT version used

0.4.0

### Compiler and Version used

Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)

### Operating System and version

macosx13.0

**Comment by waahm7** [comment]
Hi, 

Thank you for creating the issue. We will look into this issue and let you know as soon as there is any update.

**Comment by subdiox** [comment]
It's still occurring on Xcode 15.4, with `swiftSettings: [.interoperabilityMode(.Cxx)]` option. C++ interoperability has officially been released, so it would be appreciated if you support it.

**Comment by waahm7** [comment]
Thank you for the update. Please 👍 the original issue as it will help us prioritize this among other things.

**Comment by waahm7** [comment]
Thanks, this should be fixed in https://github.com/awslabs/aws-crt-swift/releases/tag/v0.38.0. Please feel free to reopen the issue if you still encounter any problems.
