### ISSUE TITLE
Refactor Enums

### ISSUE THREAD

**Issue by waahm7** [awslabs/aws-crt-swift#167]
### Describe the feature

We need to refactor enums to have sensible defaults, or make them throwable. 

### Use Case

N/A

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
Some examples

https://github.com/search?q=repo%3Aawslabs%2Faws-crt-swift%20allCases.first&type=code

**Comment by ganeshnj** [comment]
@waahm7 could estimate how long it will take to fix this?

We can the priority and effort based on that.

**Comment by smivij** [comment]
Analyze the changes and assess the impact in Q2
