### ISSUE TITLE
Separate retry backoff calculation from retry scheduling

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-crt-swift#171]
### Describe the feature

Smithy Reference Architecture defines the `RetryBackoffStrategy` type, which (translated to Swift) is:
```
public protocol RetryBackoffStrategy {
    func computeNextBackoffDelay(attempt: Int) -> TimeInterval
}
```

Calling the `computeNextBackoffDelay(attempt:)` method on this protocol allows a client to determine the delay to wait before performing a retry.  The client can then use this delay to schedule retry using the scheduling mechanism and HTTP client of their choice.

Looking at the CRT implementation of retry, `aws-c-io` does not expose such a method, even though it does calculate the needed delay internally.  Instead, it appears that the C function [aws_retry_strategy_schedule_retry](https://github.com/awslabs/aws-c-io/blob/ab77be6bf78932ec5bb357341f4bb2ca3e1103c7/include/aws/io/retry_strategy.h#L175) is provided, which calculates the delay and schedules the retry, after the appropriate delay, on CRT's own event loop.  (`aws-crt-swift` uses this C method in its `scheduleRetry(token:errorType:)` method for its own public retry interface.)

Please provide methods for determining retry backoff delay separate from the methods for scheduling retry; this will assist with compliance with the Smithy Reference Architecture and with future modularization work on the AWS SDK for Swift.

### Use Case

Allows for use of CRT's retry backoff logic with non-CRT HTTP clients.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epau** [comment]
Blocked: Needs more information on exactly what is required.
