### ISSUE TITLE
Cognito Credential Provider - CRT Analysis

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-crt-swift#189]

**Comment by waahm7** [comment]
The CRT has a [CognitoCredentialsProvider](https://github.com/awslabs/aws-c-auth/blob/main/include/aws/auth/credentials.h#L1041), which supports the [GetCredentialsForIdentity](https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetCredentialsForIdentity.html) method for fetching credentials. These credentials can be utilized by the SDK after the implementation of the binding layer.

**Comment by dayaffe** [comment]
Created issue to track creation of Swift bindings in aws-crt-swift https://github.com/awslabs/aws-crt-swift/issues/196
