### ISSUE TITLE
Concurrent SES and DynamoDB use in Lambda causes Fatal error: Tls Context failed to create.

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-crt-swift#197]
### Describe the bug

Bug issue [#1077](https://github.com/awslabs/aws-sdk-swift/issues/1077) in Swift SDK project mentions an exception that is thrown from `TLSContext` constructor in `aws-crt-swift/Source/AwsCommonRuntimeKit/io/TLSContext.swift`. The bug is caught in `smithy-swift/Sources/ClientRuntime/Networking/Http/CRT/SDKDefaultIO.swift`. The error seems to be arising from CRT side, hence submission of this issue.

### Expected Behavior

TLS Context should be successfully created.

### Current Behavior

Fatal error is thrown when creating TLS context.

### Reproduction Steps

Details in issue [#1077](https://github.com/awslabs/aws-sdk-swift/issues/1077)

### Additional Information/Context

The function is using runtime version: provided:al2.v20

### aws-crt-swift version used

0.12.0

### Compiler and Version used

Swift 5.7

### Operating System and version

Built for arm64 using the swift:5.7-amazonlinux2 image

**Comment by waahm7** [comment]
Blocked by https://github.com/awslabs/aws-sdk-swift/issues/1131

**Comment by sichanyoo** [comment]
Closing as the ticket has gone stale with no response from the customer.
