### ISSUE TITLE
posix_memalign failed to allocate memory when calling SDK with expired or missing credentials 

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-crt-swift#202]
### Describe the bug

Please refer to issue below for details
https://github.com/awslabs/aws-sdk-swift/issues/876

### Expected Behavior

Please refer to issue below for details
https://github.com/awslabs/aws-sdk-swift/issues/876

### Current Behavior

Please refer to issue below for details
https://github.com/awslabs/aws-sdk-swift/issues/876

### Reproduction Steps

Please refer to issue below for details
https://github.com/awslabs/aws-sdk-swift/issues/876

### aws-crt-swift version used

N/A

### Compiler and Version used

N/A

### Operating System and version

N/A

**Comment by jbelkins** [comment]
Attempting to reproduce.  If the problem can be reproduced and localized to CRT, this ticket will be updated, otherwise we will close it.

**Comment by dayaffe** [comment]
Closing this ticket as it could not be reproduced on the latest version.
