### ISSUE TITLE
Simple program builds with 5.10.1, fails to build with swift-6.0 with error while building aws-crt-swift

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-crt-swift#277]
### Describe the bug

See customer-provided stack trace & description from an aws-sdk-swift customer:
https://github.com/awslabs/aws-sdk-swift/discussions/1686

### Expected Behavior

aws-crt-swift should build successfully

### Current Behavior

aws-crt-swift fails to build as described in the link

### Reproduction Steps

Attempt to build on the platform & compiler specified by the customer

### aws-crt-swift version used

Latest

### Compiler and Version used

Swift 6.0

### Operating System and version

Linux / ubuntu

**Comment by waahm7** [comment]
This should be fixed in https://github.com/awslabs/aws-crt-swift/releases/tag/v0.34.0.
