### ISSUE TITLE
Profile credential provider crashes SDK on deallocation

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-crt-swift#280]
### Describe the bug

The AWS SDK for Swift has a profile credential provider that is built with an implementation from this project:
https://github.com/awslabs/aws-sdk-swift/blob/main/Sources/Core/AWSSDKIdentity/Sources/AWSSDKIdentity/AWSCredentialIdentityResolvers/ProfileAWSCredentialIdentityResolver.swift#L61

This credentials provider does resolve credentials successfully from a profile, but when the credentials provider is deallocated, the CRT credentials provider crashes on `EXC_BAD_ACCESS` here due to the `shutdownCallbackOptions.shutdownCallback` property being nil:
https://github.com/awslabs/aws-crt-swift/blob/main/Source/AwsCommonRuntimeKit/crt/ShutdownCallbackCore.swift#L61

Here is the Swift snippet that uses the AWSSTS service client to cause the crash:
```swift
import AWSSTS
import AWSSDKIdentity

@main
struct GetCallerIdentity {

    static func main() async throws {
        let resolver = try AWSSDKIdentity.ProfileAWSCredentialIdentityResolver(profileName: "donothing")
        let config = try await STSClient.Config(awsCredentialIdentityResolver: resolver)
        let client = STSClient(config: config)
        let input = GetCallerIdentityInput()
        do {
            let output = try await client.getCallerIdentity(input: input)
            let userID = String(describing: output.userId)
            let account = String(describing: output.account)
            print("Request succeeded")
            print("User ID: \(userID)")
            print("Account: \(account)")
        } catch {
            print("Request failed")
            print("Error: \(error)")
        }
    }
}
```

Here is the `~/.aws/config` file, credentials are configured in a separate file:
```
[default]
region = us-east-1

[profile donothing]
role_arn = arn:aws:iam::1234567890:role/DoNothingRole
```

### Expected Behavior

Credentials provider should deallocate successfully

### Current Behavior

Credentials provider crashes as indicated

### Reproduction Steps

Run the code above, observe crash after successful profile resolution

### aws-crt-swift version used

0.33.0

### Compiler and Version used

Xcode 15.4

### Operating System and version

macOS 14.6.1

**Comment by jbelkins** [comment]
An aws-sdk-swift customer reported a similar crash, that happens on credential provider deallocation.
https://github.com/awslabs/aws-sdk-swift/issues/1714

Of note, the customer defined a profile that assumes a role, similar to what was done above.

**Comment by waahm7** [comment]
Fixed in https://github.com/awslabs/aws-crt-swift/releases/tag/v0.36.0.
