### ISSUE TITLE
SSO Credential Provider

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-crt-swift#95]
### Describe the feature

--/seps/accepted/shared/sso-provider.md

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Will do the SDK work for this under https://github.com/awslabs/aws-sdk-swift/issues/236 .  Closing this ticket since CRT work is shipped.
