### ISSUE TITLE
Event Steaming encoding decoding

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-crt-swift#99]
### Describe the feature

Bindings for encode and decode messages.

### Use Case

https://github.com/awslabs/smithy-swift/pull/460

CRT already has support for event stream, creating binding is preferred to not create duplication in Swift.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by waahm7** [comment]
I have added the support in 0.5.3.
